apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: jaeger-proxy-tls
  labels:
    app: jaeger-proxy
  name: jaeger-proxy
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
  - name: jaeger-proxy
    port: 9091
    protocol: TCP
    targetPort: jaeger-proxy
  selector:
    app: jaeger-proxy
  sessionAffinity: None
  type: ClusterIP
